// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RussianWeb.Models;

namespace RussianWeb.Migrations
{
    [DbContext(typeof(RussianWebDbContext))]
    partial class RussianWebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RussianWeb.Models.Post", b =>
                {
                    b.Property<string>("Onvan")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("KholaseyePost");

                    b.Property<string>("MatneKamelePost");

                    b.Property<DateTime>("TarikheEnteshar");

                    b.HasKey("Onvan");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("RussianWeb.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
